### ISSUE TITLE
index2.js not appear in source.

### ISSUE THREAD

**Issue by Manoj-Madushantha** [CodeNerve/CodeNerve.github.io#2]
<script type="text/javascript", src="index2.js">
    </script>
above line appeared in index.html.  but index2.js not appear in source files.
I run the code but not display the typer text on chrome browser.

**Comment by s-adochi** [comment]
did you find the solution to that? i have the same problem

**Comment by Pradyuman7** [comment]
@Manoj-Madushantha it was a typo from the previous version of the code, which I forgot to remove, but the code should be working. Have you hosted it properly on your GitHub?

**Comment by Pradyuman7** [comment]
This issue is being closed due to inactivity.
